add_newline = false

format = """
$directory\
$character\
"""

right_format = """$python $git_branch"""

[git_branch]
format = '[$branch(:$remote_branch)]($style) '

[python]
format = '[$virtualenv]($style)'

[character]
format = "\\$ "
